services:
    backend:
        build:
            context: .
            target: final
            dockerfile: ./FinanceManagementAPI/Dockerfile
        ports:
            - "5800:8080"
        volumes:
            - ./db-data:/app/database
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
#    frontend:
#        build:
#            context: ./financemanagementwebclient
#            target: runner
#            dockerfile: ./Dockerfile
#        ports:
#            - "5900:8080"
#        environment:
#           - NODE_ENV=production
#volumes:
#    db-data:
  